---
description: 'AUTHORS: __Julien Ruffault (julien.ruff@gmail.com), Nicolas Martin-StPaul
  (nicolas.martin@inrae.fr)__'
output-file: conversions_utils.html
title: Conversions functions utils

---


<!-- WARNING: THIS FILE WAS AUTOGENERATED! DO NOT EDIT! -->

---

[source](https://github.com/ecamo19/pysureau/blob/master/pysureau/conversions_utils.py#L26){target="_blank" style="float:right; font-size:smaller"}

### convert_vwc_to_sws

>      convert_vwc_to_sws (volumetric_water_content_x:float,
>                          layer_thickness:float, rfc:float=0)

*Convert soil volumetric water content (VWC) to soil water stock (SWS). The volume of the water quantity per square metre results in the corresponding water stock height (m3 water per m2 soil as height in mm)*

|    | **Type** | **Default** | **Details** |
| -- | -------- | ----------- | ----------- |
| volumetric_water_content_x | float |  | Volumetric water content (m3.m-3) |
| layer_thickness | float |  | Thickness of the soil layer (in m) |
| rfc | float | 0 | Rock fragment content of the soil layer (%) |
| **Returns** | **float** |  | **Soil Water Stock (mm)** |


::: {#cell-3 .cell}
``` {.python .cell-code}
convert_vwc_to_sws(volumetric_water_content_x = 0.5, 
                   rfc = 50, 
                   layer_thickness = 1)
```

::: {.cell-output .cell-output-display}
```
250.0
```
:::
:::


---

[source](https://github.com/ecamo19/pysureau/blob/master/pysureau/conversions_utils.py#L37){target="_blank" style="float:right; font-size:smaller"}

### convert_sws_to_vwc

>      convert_sws_to_vwc (soil_water_stock_x:float, layer_thickness:float,
>                          rfc:float=0)

*Convert soil water stock (SWS) to volumetric water content (VWC). Convert soil water stock (quantity as height in mm per m2 soil) to volumetric water content (m3.m-3) by accounting for the respective layer thickness and rock fragment content.*

|    | **Type** | **Default** | **Details** |
| -- | -------- | ----------- | ----------- |
| soil_water_stock_x | float |  | Soil water stock (mm) |
| layer_thickness | float |  | Thickness of the soil layer (in m) |
| rfc | float | 0 | Rock fraction  content of the soil layer (%) |
| **Returns** | **float** |  | **Volumetric Water Content (m3.m-3)** |


::: {#cell-5 .cell}
``` {.python .cell-code}
convert_sws_to_vwc(soil_water_stock_x = 250, 
                   rfc = 50, 
                   layer_thickness = 1)
```

::: {.cell-output .cell-output-display}
```
0.5
```
:::
:::


---

[source](https://github.com/ecamo19/pysureau/blob/master/pysureau/conversions_utils.py#L48){target="_blank" style="float:right; font-size:smaller"}

### convert_ksat_cmday_to_ksat_micromol

>      convert_ksat_cmday_to_ksat_micromol (ksat_cmday:float)

*Convert Saturated Hydraulic Conductivity?(ksat) units from cm/day (ESDAC unit) to mmol/s/m/MPa (Sureau unit)*

|    | **Type** | **Details** |
| -- | -------- | ----------- |
| ksat_cmday | float | Saturated hydraulic conductivity? in centimeters per day |
| **Returns** | **float** | **Saturated Hydraulic Conductivity?(ksat) in mmol/s/m/MPa** |


---

[source](https://github.com/ecamo19/pysureau/blob/master/pysureau/conversions_utils.py#L64){target="_blank" style="float:right; font-size:smaller"}

### convert_rate_to_molm_s_m_mpa

>      convert_rate_to_molm_s_m_mpa (rate_x:float, molm:float=18.01528,
>                                    pa:float=9.80665, xfac:float=8640000)

*Convert a hydraulic rate to SurEau-Ecos rate*

|    | **Type** | **Default** | **Details** |
| -- | -------- | ----------- | ----------- |
| rate_x | float |  | A rate in L/T. The default assumes cm/d to be converted to m/s |
| molm | float | 18.01528 | Molar mass of h2o (g mol-1) |
| pa | float | 9.80665 | Hydrostatic pressure (Pa mm-1) |
| xfac | float | 8640000 | Divisor converting rate (L T-1) to (m s-1). Value 8640000 comes from 24 * 60 ** 2 * 100 |
| **Returns** | **float** |  | **Converted rate to SurEau-Ecos unit (mmol.h2o s-1 m-1.soil MPa-1)** |


::: {#cell-8 .cell}
``` {.python .cell-code}
convert_rate_to_molm_s_m_mpa(1)
```

::: {.cell-output .cell-output-display}
```
655.1255924715483
```
:::
:::


---

[source](https://github.com/ecamo19/pysureau/blob/master/pysureau/conversions_utils.py#L78){target="_blank" style="float:right; font-size:smaller"}

### convert_molm_s_m_mpa_to_rate

>      convert_molm_s_m_mpa_to_rate (rate_x:float, molm:float=18.01528,
>                                    pa:float=9.80665, xfac:float=8640000)

*Convert SurEau-Ecos rate to a hydraulic rate. Inverse of convert_rate_to_molm_s_m_mpa() funtion.*

|    | **Type** | **Default** | **Details** |
| -- | -------- | ----------- | ----------- |
| rate_x | float |  | # Unknown parameter definition |
| molm | float | 18.01528 | Molar mass of h2o (g mol-1) |
| pa | float | 9.80665 | Hydrostatic pressure (Pa mm-1) |
| xfac | float | 8640000 | Divisor converting rate (L T-1) to (m s-1). Value 8640000 comes from 24 * 60 ** 2 * 100 |
| **Returns** | **float** |  | **A rate (L/T)** |


::: {#cell-10 .cell}
``` {.python .cell-code}
convert_molm_s_m_mpa_to_rate(655.1255924715483)
```

::: {.cell-output .cell-output-display}
```
0.9999999999999999
```
:::
:::


---

[source](https://github.com/ecamo19/pysureau/blob/master/pysureau/conversions_utils.py#L89){target="_blank" style="float:right; font-size:smaller"}

### convert_mpa_to_m

>      convert_mpa_to_m (mpa_x:float, pa:float=9.80665)

*Conversion of hydrostatic pressure (MPa) to pressure height (m)*

|    | **Type** | **Default** | **Details** |
| -- | -------- | ----------- | ----------- |
| mpa_x | float |  | Hydrostatic pressure in MPa |
| pa | float | 9.80665 | Hydrostatic pressure (Pa mm-1) |
| **Returns** | **float** |  | **Pressure height in meters** |


::: {#cell-12 .cell}
``` {.python .cell-code}
convert_mpa_to_m(1)
```

::: {.cell-output .cell-output-display}
```
101.97162129779284
```
:::
:::


---

[source](https://github.com/ecamo19/pysureau/blob/master/pysureau/conversions_utils.py#L99){target="_blank" style="float:right; font-size:smaller"}

### convert_m_to_mpa

>      convert_m_to_mpa (m_x:float, pa:float=9.80665)

*Conversion of pressure height (m) to hydrostatic pressure (MPa)*

|    | **Type** | **Default** | **Details** |
| -- | -------- | ----------- | ----------- |
| m_x | float |  | Pressure height in meters |
| pa | float | 9.80665 | Hydrostatic pressure (Pa mm-1) |
| **Returns** | **float** |  |  |


::: {#cell-14 .cell}
``` {.python .cell-code}
convert_m_to_mpa(101.97162129779284)
```

::: {.cell-output .cell-output-display}
```
1.0
```
:::
:::


---

[source](https://github.com/ecamo19/pysureau/blob/master/pysureau/conversions_utils.py#L109){target="_blank" style="float:right; font-size:smaller"}

### convert_pf_to_hpa

>      convert_pf_to_hpa (x:float)

*Function lacks definition, documentation needs to be improved.*

|    | **Type** | **Details** |
| -- | -------- | ----------- |
| x | float | Unknown parameter definition |
| **Returns** | **float** | **Unknown parameter definition** |


::: {#cell-16 .cell}
``` {.python .cell-code}
convert_pf_to_hpa(1.8)
```

::: {.cell-output .cell-output-display}
```
63.09573444801933
```
:::
:::


---

[source](https://github.com/ecamo19/pysureau/blob/master/pysureau/conversions_utils.py#L117){target="_blank" style="float:right; font-size:smaller"}

### convert_hpa_to_pf

>      convert_hpa_to_pf (x:float)

*Function lacks definition, documentation needs to be improved.*

|    | **Type** | **Details** |
| -- | -------- | ----------- |
| x | float | Unknown parameter definition |
| **Returns** | **float** | **Unknown parameter definition** |


::: {#cell-18 .cell}
``` {.python .cell-code}
convert_hpa_to_pf(63.09573444801933)
```

::: {.cell-output .cell-output-display}
```
1.8
```
:::
:::


---

[source](https://github.com/ecamo19/pysureau/blob/master/pysureau/conversions_utils.py#L125){target="_blank" style="float:right; font-size:smaller"}

### convert_vg_psi_to_theta

>      convert_vg_psi_to_theta (vg_psi_x:float, theta_s:float, theta_r:float,
>                               a:float, n:float)

*Unit conversion from soil matric potential (Psi) to volumetric water content (Theta) using the Mualem-van-Genuchten pedotransfer function*

|    | **Type** | **Details** |
| -- | -------- | ----------- |
| vg_psi_x | float | Soil matric potential (hPa) |
| theta_s | float | Saturated water content (L3 L-3) |
| theta_r | float | Residual water content (L3 L-3) |
| a | float | Parameter related to the inverse of the air-entry pressure (unitless?) |
| n | float | Parameter related to the pore-size distribution (unitless) |
| **Returns** | **float** | **Volumetric water content** |


::: {#cell-20 .cell}
``` {.python .cell-code}
convert_vg_psi_to_theta(vg_psi_x = np.array([-1e6, -1e2, 0]), 
                        theta_s = 0.5, 
                        theta_r = 0.1, 
                        a = 0.05, 
                        n = 1.5)
```

::: {.cell-output .cell-output-display}
```
array([0.10178885, 0.27384953, 0.5       ])
```
:::
:::


---

[source](https://github.com/ecamo19/pysureau/blob/master/pysureau/conversions_utils.py#L138){target="_blank" style="float:right; font-size:smaller"}

### convert_vg_theta_to_psi

>      convert_vg_theta_to_psi (vwc_theta_x:float, theta_s:float, theta_r:float,
>                               a:float, n:float)

*Unit conversion from volumetric water content (Theta) to soil matric potential (Psi) using the Mualem-van-Genuchten pedotransfer function*

|    | **Type** | **Details** |
| -- | -------- | ----------- |
| vwc_theta_x | float | volumetric water content (L3 L-3) |
| theta_s | float | Saturated water content (L3 L-3) |
| theta_r | float | Residual water content (L3 L-3) |
| a | float | Parameter related to the inverse of the air-entry pressure (unitless?) |
| n | float | Parameter related to the pore-size distribution (unitless) |
| **Returns** | **float** | **Soil matric potential** |


::: {#cell-22 .cell}
``` {.python .cell-code}
convert_vg_theta_to_psi(vwc_theta_x = np.array([.1, .3, .5]), 
                        theta_s = 0.5, 
                        theta_r = 0.1, 
                        a = 0.05, 
                        n = 1.5)
```

::: {.cell-output .cell-output-stderr}
```
/tmp/ipykernel_9862/3671110304.py:16: RuntimeWarning: divide by zero encountered in power
  return (theta_eff ** (-1/(1 - 1/n)) - 1) ** (1/n) / a * (-1)
```
:::

::: {.cell-output .cell-output-display}
```
array([       -inf, -73.1861142,  -0.       ])
```
:::
:::


---

[source](https://github.com/ecamo19/pysureau/blob/master/pysureau/conversions_utils.py#L154){target="_blank" style="float:right; font-size:smaller"}

### convert_vwc_to_rew

>      convert_vwc_to_rew (vwc_x:float, theta_s:float, theta_r:float)

*Conversion from volumetric water content to relative extractable water (REW). REW is the volumetric water content normalised to saturation capacity (REW=1) and residual capacity (REW=0)*

|    | **Type** | **Details** |
| -- | -------- | ----------- |
| vwc_x | float | Volumetric Water Content (L3*L-3) |
| theta_s | float | Saturated water content (L3 L-3) |
| theta_r | float | Residual water content (L3 L-3) |
| **Returns** | **float** | **Relative Extractable water** |


::: {#cell-24 .cell}
``` {.python .cell-code}
convert_vwc_to_rew(vwc_x = np.array([0.1, 0.3, 0.5]), 
                   theta_s = 0.5, 
                   theta_r = 0.1)
```

::: {.cell-output .cell-output-display}
```
array([0. , 0.5, 1. ])
```
:::
:::


---

[source](https://github.com/ecamo19/pysureau/blob/master/pysureau/conversions_utils.py#L165){target="_blank" style="float:right; font-size:smaller"}

### convert_rew_to_vwc

>      convert_rew_to_vwc (rew_x:float, theta_s:float, theta_r:float)

*Conversion from relative extractable water to volumetric water*

|    | **Type** | **Details** |
| -- | -------- | ----------- |
| rew_x | float | Relative Extractable water (rew) |
| theta_s | float | Saturated water content (L3 L-3) |
| theta_r | float | Residual water content (L3 L-3) |
| **Returns** | **float** | **Volumetric Water Content (L3*L-3)** |


::: {#cell-26 .cell}
``` {.python .cell-code}
convert_rew_to_vwc(rew_x = np.array([0, 0.5, 1]), 
                   theta_s = 0.5, 
                   theta_r = 0.1)
```

::: {.cell-output .cell-output-display}
```
array([0.1, 0.3, 0.5])
```
:::
:::


---

[source](https://github.com/ecamo19/pysureau/blob/master/pysureau/conversions_utils.py#L175){target="_blank" style="float:right; font-size:smaller"}

### convert_mmol_to_m3

>      convert_mmol_to_m3 (mmol_h2o_x:float, molm:float=18.01528, pw:float=998)

*Stochiometric conversion between volume and molarity  In case of converting from or to millimetres (mm), the actual unit is the volume divided by its area, resulting in a depth given in millimetres.*

|    | **Type** | **Default** | **Details** |
| -- | -------- | ----------- | ----------- |
| mmol_h2o_x | float |  | Unit to be converted (mmol, m³ or mm depending on the used function |
| molm | float | 18.01528 | Molar mass of h2o (g mol-1) |
| pw | float | 998 | Density of water (kg m-3.h2o) |
| **Returns** | **float** |  | **Unknown parameter** |


::: {#cell-28 .cell}
``` {.python .cell-code}
convert_mmol_to_m3(1)
```

::: {.cell-output .cell-output-display}
```
1.8051382765531063e-08
```
:::
:::


::: {#cell-29 .cell}
``` {.python .cell-code}
def convert_m3_to_mmol(
    m3_x:float, 
    molm: float = 18.01528,  # Molar mass of h2o (g mol-1)
    pw: float = 998,  # Density of water (kg m-3.h2o)
) -> float: # 
    
    'Stochiometric conversion between volume and molarity  In case of converting from or to millimetres (mm), the actual unit is the volume divided by its area, resulting in a depth given in millimetres.'
    
    return m3_x/molm * pw * 1e6
```
:::


::: {#cell-30 .cell}
``` {.python .cell-code}
convert_m3_to_mmol(1.8051382765531063e-08)
```

::: {.cell-output .cell-output-display}
```
1.0
```
:::
:::


---

[source](https://github.com/ecamo19/pysureau/blob/master/pysureau/conversions_utils.py#L186){target="_blank" style="float:right; font-size:smaller"}

### convert_mmol_to_mm

>      convert_mmol_to_mm (mmol_h2o_x:float, molm:float=18.01528, pw:float=998)

*Stochiometric conversion between volume and molarity  In case of converting from or to millimetres (mm), the actual unit is the volume divided by its area, resulting in a depth given in millimetres.*

|    | **Type** | **Default** | **Details** |
| -- | -------- | ----------- | ----------- |
| mmol_h2o_x | float |  | Unit to be converted (mmol, m³ or mm depending on the used function |
| molm | float | 18.01528 | Molar mass of h2o (g mol-1) |
| pw | float | 998 | Density of water (kg m-3.h2o) |
| **Returns** | **float** |  | **Unknown parameter** |


::: {#cell-32 .cell}
``` {.python .cell-code}
convert_mmol_to_mm(1)
```

::: {.cell-output .cell-output-display}
```
1.8051382765531063e-05
```
:::
:::


::: {#cell-33 .cell}
``` {.python .cell-code}
def convert_mm_to_mmol(
    mm_x:float,
    molm: float = 18.01528,  # Molar mass of h2o (g mol-1)
    pw: float = 998,  # Density of water (kg m-3.h2o)
    )-> float: 
    
    'Stochiometric conversion between volume and molarity  In case of converting from or to millimetres (mm), the actual unit is the volume divided by its area, resulting in a depth given in millimetres.'
    
    return mm_x / molm * pw * 1e3
```
:::


::: {#cell-34 .cell}
``` {.python .cell-code}
convert_mm_to_mmol(1.8051382765531063e-05)
```

::: {.cell-output .cell-output-display}
```
1.0
```
:::
:::


---

[source](https://github.com/ecamo19/pysureau/blob/master/pysureau/conversions_utils.py#L196){target="_blank" style="float:right; font-size:smaller"}

### convert_compartment_leaf_to_soil

>      convert_compartment_leaf_to_soil (x:float, lai:float=1)

*Function lacks definition, documentation needs to be improved.*

|    | **Type** | **Default** | **Details** |
| -- | -------- | ----------- | ----------- |
| x | float |  | Unknown parameter definition m2.leaf |
| lai | float | 1 | Leaf Area Index |
| **Returns** | **float** |  | **Unknown parameter m2.soil** |


---

[source](https://github.com/ecamo19/pysureau/blob/master/pysureau/conversions_utils.py#L204){target="_blank" style="float:right; font-size:smaller"}

### convert_compartment_soil_to_leaf

>      convert_compartment_soil_to_leaf (x:float, lai:float=1)

*Function lacks definition, documentation needs to be improved.*

|    | **Type** | **Default** | **Details** |
| -- | -------- | ----------- | ----------- |
| x | float |  | Unknown parameter definition m2.soil |
| lai | float | 1 | Leaf Area Index |
| **Returns** | **float** |  | **Unknown parameter m2.leaf** |


---

[source](https://github.com/ecamo19/pysureau/blob/master/pysureau/conversions_utils.py#L212){target="_blank" style="float:right; font-size:smaller"}

### convert_compartment_stem_to_leaf

>      convert_compartment_stem_to_leaf (stem_x:float, hv:float)

*Function lacks definition, documentation needs to be improved.*

|    | **Type** | **Details** |
| -- | -------- | ----------- |
| stem_x | float | Unknown parameter definition m2.stem |
| hv | float | Huber value (sap wood / leaf area) |
| **Returns** | **float** | **Unknown parameter m2.leaf** |


---

[source](https://github.com/ecamo19/pysureau/blob/master/pysureau/conversions_utils.py#L220){target="_blank" style="float:right; font-size:smaller"}

### convert_compartment_leaf_to_stem

>      convert_compartment_leaf_to_stem (leaf_x:float, hv:float)

*Function lacks definition, documentation needs to be improved.*

|    | **Type** | **Details** |
| -- | -------- | ----------- |
| leaf_x | float | Unknown parameter definition m2.leaf |
| hv | float | Huber value (sap wood / leaf area) |
| **Returns** | **float** | **Unknown parameter m2.stem** |


---

[source](https://github.com/ecamo19/pysureau/blob/master/pysureau/conversions_utils.py#L228){target="_blank" style="float:right; font-size:smaller"}

### convert_compartment_stem_to_soil

>      convert_compartment_stem_to_soil (stem_x:float, swi:float)

*Function lacks definition, documentation needs to be improved.*

|    | **Type** | **Details** |
| -- | -------- | ----------- |
| stem_x | float | Unknown parameter definition |
| swi | float | Sap wood index (m2.sapwood m-2.soil) |
| **Returns** | **float** | **Unknown parameter m2.soil** |


---

[source](https://github.com/ecamo19/pysureau/blob/master/pysureau/conversions_utils.py#L236){target="_blank" style="float:right; font-size:smaller"}

### convert_compartment_soil_to_stem

>      convert_compartment_soil_to_stem (soil_x:float, swi:float)

*Function lacks definition, documentation needs to be improved.*

|    | **Type** | **Details** |
| -- | -------- | ----------- |
| soil_x | float | Unknown parameter definition |
| swi | float | Sap wood index (m2.sapwood m-2.soil) |
| **Returns** | **float** | **Unknown parameter m2.stem** |


::: {#cell-41 .cell}
``` {.python .cell-code}
def convert_stock_to_flux(x:float,
                          dt:int # Time step length in seconds
                          ) -> float: #
    
    'Function lacks definition, documentation needs to be improved.'
    return  x / dt
```
:::


::: {#cell-42 .cell}
``` {.python .cell-code}
def convert_flux_to_stock(x:float,
                          dt:int # Time step length in seconds
                          ) -> float: #
    
    'Function lacks definition, documentation needs to be improved.'
    return x*dt
```
:::


---

[source](https://github.com/ecamo19/pysureau/blob/master/pysureau/conversions_utils.py#L245){target="_blank" style="float:right; font-size:smaller"}

### convert_stock_mm_soil_to_flux_mmol_leaf

>      convert_stock_mm_soil_to_flux_mmol_leaf (stand_water_stock_x:float,
>                                               lai:float, dt:float,
>                                               molm:float=18.01528,
>                                               pw:float=998)

*Converts a stand level water quantity (mm, i.e. L m-2Soil) over a defined time period to a leaf area-based flux (mmol m-2Leaf s-1) for a given leaf area index*

|    | **Type** | **Default** | **Details** |
| -- | -------- | ----------- | ----------- |
| stand_water_stock_x | float |  | Stand level water stock for a given LAI in mm(L m-2Soil) over the period of time considered |
| lai | float |  | Leaf area Index |
| dt | float |  | Time step length in seconds |
| molm | float | 18.01528 | Molar mass of h2o (g mol-1) |
| pw | float | 998 | Density of water (kg m-3.h2o) |
| **Returns** | **float** |  | **Instantaneous leaf area-based flux (mmol m-2Leaf s-1)** |


::: {#cell-44 .cell}
``` {.python .cell-code}
convert_stock_mm_soil_to_flux_mmol_leaf(stand_water_stock_x = 2, 
                                        dt = 60**2, 
                                        lai = 3)
```

::: {.cell-output .cell-output-display}
```
10.25878114660526
```
:::
:::


::: {#cell-45 .cell}
``` {.python .cell-code}
def convert_flux_mmol_leaf_to_stock_mm_soil(
    leaf_area_based_flux:float, # Instantaneous leaf area-based flux to be converted (mmol m-2Leaf s-1)
    dt: float,  # Time step length in seconds
    lai: float,  # Leaf area Index 
    molm: float = 18.01528,  # Molar mass of h2o (g mol-1)
    pw: float = 998,  # Density of water (kg m-3.h2o)
) -> float: # Stand level water stock for a given LAI in mm (L m-2Soil) over the period of time considered.
    
    'Converts an instantaneous leaf area-based flux (mmol m-2Leaf s-1) to a stand level water quantity (mm, i.e. L m-2Soil) for a given leaf area index over a defined time period.'
    stock  = convert_flux_to_stock(x = leaf_area_based_flux, dt = dt)
    mm = convert_mmol_to_mm(mmol_h2o_x = stock, molm = molm, pw = pw)
    
    return convert_compartment_leaf_to_soil(x = mm, lai = lai)
```
:::


::: {#cell-46 .cell}
``` {.python .cell-code}
# 10 mmol/s over a period of 1 hour with an LAI of 3 m² is converted to
# millimetres of soil water stock (L/m²)

convert_flux_mmol_leaf_to_stock_mm_soil(leaf_area_based_flux = 10, 
                                      dt = 60**2, 
                                      lai = 3)
```

::: {.cell-output .cell-output-display}
```
1.9495493386773552
```
:::
:::


---

[source](https://github.com/ecamo19/pysureau/blob/master/pysureau/conversions_utils.py#L272){target="_blank" style="float:right; font-size:smaller"}

### convert_optim_mm_soil_to_mmol_leaf

>      convert_optim_mm_soil_to_mmol_leaf (instaneous_flux:float, dt:float,
>                                          lai:float)

*Converts a stand level water quantity (mm, i.e. L m-2Soil) over a defined time period to a leaf area-based flux (mmol m-2Leaf s-1) for a given leaf area index.*

|    | **Type** | **Details** |
| -- | -------- | ----------- |
| instaneous_flux | float | Stand level water stock for a given LAI in mm (L m-2Soil) over the period of time considered |
| dt | float | Time step length in seconds |
| lai | float | Leaf area index |
| **Returns** | **float** | **Instantaneous leaf area-based flux (mmol m-2Leaf s-1** |


---

[source](https://github.com/ecamo19/pysureau/blob/master/pysureau/conversions_utils.py#L296){target="_blank" style="float:right; font-size:smaller"}

### convert_optim_mmol_leaf_to_mm_soil

>      convert_optim_mmol_leaf_to_mm_soil (x:float, dt:float, lai:float)

*Converts an instantaneous leaf area-based flux (mmol m-2Leaf s-1) to a stand level water quantity*

|    | **Type** | **Details** |
| -- | -------- | ----------- |
| x | float | Instantaneous leaf area-based flux to be converted (mmol m-2Leaf s-1) |
| dt | float | Time step length in seconds |
| lai | float | Leaf area index |
| **Returns** | **float** | **Stand level water stock for a given LAI in mm (L m-2Soil) over the period of time considered** |


## Functions of conversion and temporal disagregation of climatic variable as well as PET computation

---

[source](https://github.com/ecamo19/pysureau/blob/master/pysureau/conversions_utils.py#L308){target="_blank" style="float:right; font-size:smaller"}

### compute_vpd_from_temp_rh

>      compute_vpd_from_temp_rh (relative_humidity:float, temperature:float,
>                                air_pressure:float=101325)

*Compute vapor pressure deficit (VPD) from air relative humidity (rh) and air temperature (temp)*

|    | **Type** | **Default** | **Details** |
| -- | -------- | ----------- | ----------- |
| relative_humidity | float |  | Air relative_humidity (%) |
| temperature | float |  | Air temperature (degrees Celsius) |
| air_pressure | float | 101325 | Air pressure (Pa) |
| **Returns** | **float** |  |  |


#### __Example: Compute VPD__

::: {#cell-52 .cell}
``` {.python .cell-code}
compute_vpd_from_temp_rh(relative_humidity=70, temperature=55)
```

::: {.cell-output .cell-output-display}
```
array([4.76019573])
```
:::
:::


::: {#cell-53 .cell}
``` {.python .cell-code}
compute_vpd_from_temp_rh(relative_humidity=25, temperature=np.array([80, 90]))
```

::: {.cell-output .cell-output-display}
```
array([36.10624792, 53.70318944])
```
:::
:::


---

[source](https://github.com/ecamo19/pysureau/blob/master/pysureau/conversions_utils.py#L403){target="_blank" style="float:right; font-size:smaller"}

### compute_slope_sat

>      compute_slope_sat (tmoy:float)

*Compute slope of the saturation vapour pressure function (AO 1998)*

|    | **Type** | **Details** |
| -- | -------- | ----------- |
| tmoy | float | Mean daily temperature in °C |
| **Returns** | **float** | **Slope of the saturation vapour pressure function** |


---

[source](https://github.com/ecamo19/pysureau/blob/master/pysureau/conversions_utils.py#L416){target="_blank" style="float:right; font-size:smaller"}

### compute_pet

>      compute_pet (tmoy:float, net_radiation:float, g:float=0, vpd:float=None,
>                   wind_speed_u:float=None, pt_coeff:float=None,
>                   formulation:str='pt')

*Calcule Potential Evapotranspiration (mm) PET using Pristeley Taylor (pt) or Penmman (penman) formulation*

|    | **Type** | **Default** | **Details** |
| -- | -------- | ----------- | ----------- |
| tmoy | float |  | Mean temperature over the considered time step (degrees Celsius) |
| net_radiation | float |  | Cumulative Net radiation over the considered time sep (MJ.m2) |
| g | float | 0 | Energy storage parameter. Represents ground heat flux |
| vpd | float | None | Vapor pressure deficit (kpa) for calculating etp using the Penman-Monteith (penman) formulation |
| wind_speed_u | float | None | Wind speed (m.s-1) for calculating etp using the Penman-monteith (penman) formulation |
| pt_coeff | float | None | An empirical constant accounting for the vapor pressure deficit and resistance values. Typically, α is 1.26 for open bodies of water, but has a wide range of values from less than 1 (humid conditions) to almost 2 (arid conditions). |
| formulation | str | pt | String indicating which formulation to use (Pristeley Taylor (pt) or Penman-Monteith (penman)) for calculating potential evapotranspiration |
| **Returns** | **float** |  | **Potential evapotranspiration (PET) (mm)** |


#### __Example: Compute Potential Evapotranspiration__

::: {#cell-57 .cell}
``` {.python .cell-code}
compute_pet(tmoy=80, net_radiation=25, formulation='pt')
```
:::


::: {#cell-58 .cell}
``` {.python .cell-code}
compute_pet(
    tmoy=20, net_radiation=1, wind_speed_u=2, vpd=2, formulation='penman'
)
```
:::


::: {#cell-59 .cell}
``` {.python .cell-code}
compute_pet(tmoy=15, net_radiation = 5, wind_speed_u =2, vpd =1, formulation = "penman")
```

::: {.cell-output .cell-output-display}
```
1.126055124868983
```
:::
:::


---

[source](https://github.com/ecamo19/pysureau/blob/master/pysureau/conversions_utils.py#L537){target="_blank" style="float:right; font-size:smaller"}

### calculate_radiation_diurnal_pattern

>      calculate_radiation_diurnal_pattern (time_of_day:int, day_length:int)

*Calculated diurnal pattern of temperature assuming a sinusoidal pattern with T = tmin at sunrise and T = (tmin + tmax)/2 at sunset. From sunset to sunrise follows a linear trend*

|    | **Type** | **Details** |
| -- | -------- | ----------- |
| time_of_day | int | Numeric value of vector indicating the time of the day (in seconds) |
| day_length | int | Value indicating the duration of the day (in seconds). Calculated using the [`day_length`](https://ecamo19.github.io/pysureau/climate_utils.html#day_length) function |
| **Returns** | **float** |  |


#### __Example: Calculate radiation diurnal pattern__

::: {#cell-62 .cell}
``` {.python .cell-code}
calculate_radiation_diurnal_pattern(time_of_day=1, day_length=40)
```
:::


---

[source](https://github.com/ecamo19/pysureau/blob/master/pysureau/conversions_utils.py#L600){target="_blank" style="float:right; font-size:smaller"}

### calculate_temperature_diurnal_pattern

>      calculate_temperature_diurnal_pattern (time_of_day:float, day_length:int,
>                                             tmin:float, tmax:float,
>                                             tmin_prev:float, tmax_prev:float,
>                                             tmin_next:float)

*Calculated diurnal pattern of temperature assuming a sinusoidal pattern with T = tmin at sunrise and T = (tmin+tmax)/2 at sunset. From sunset to sunrise follows a linear trend*

|    | **Type** | **Details** |
| -- | -------- | ----------- |
| time_of_day | float | Value of vector indicating the time of the day (in seconds from sunrise) |
| day_length | int | Value indicating the duration of the day (in seconds). Calculated using the [`day_length`](https://ecamo19.github.io/pysureau/climate_utils.html#day_length) function |
| tmin | float | Minimum temperature (in degrees C) of the target day of the year |
| tmax | float | Maximum temperature (in degrees C) of the target day of the year |
| tmin_prev | float | Minimum temperature (in degrees C) of the previous target day of the year |
| tmax_prev | float | Maximum temperature (in degrees C) of the previous target day of the year |
| tmin_next | float | Minimum temperature (in degrees C) of the next target day of the year |
| **Returns** | **float** | **Temperature at the given time** |


#### __Example: calculate the temperature diurnal pattern__

::: {#cell-65 .cell}
``` {.python .cell-code}
calculate_temperature_diurnal_pattern(
    time_of_day=0,
    day_length=0,
    tmin=0.6,
    tmax=8.2,
    tmin_prev=2.6,
    tmax_prev=11.3,
    tmin_next=4.7,
)
```
:::


---

[source](https://github.com/ecamo19/pysureau/blob/master/pysureau/conversions_utils.py#L642){target="_blank" style="float:right; font-size:smaller"}

### calculate_rh_diurnal_pattern

>      calculate_rh_diurnal_pattern (temperature:float, rhmin:float,
>                                    rhmax:float, tmin:float, tmax:float)

*Calculate diurnal pattern of relative humidity from temperature*

|    | **Type** | **Details** |
| -- | -------- | ----------- |
| temperature | float | Numeric value providing the target temperature (degrees C) at which we should compute target rh |
| rhmin | float | Numeric value indicating the minimum relative humidity (%) of the day |
| rhmax | float | Numeric value indicating the maximum relative humidity (%) of the day |
| tmin | float | Numeric value indicating the minimum daily temperature (degrees C) |
| tmax | float | Numeric value indicating the maximum daily temperature (degrees C) |
| **Returns** | **float** | **Relative humidity at given temperature** |


::: {#cell-67 .cell}
``` {.python .cell-code}
calculate_rh_diurnal_pattern(17, 40, 80, 15, 25)
```

::: {.cell-output .cell-output-display}
```
72.0
```
:::
:::


---

[source](https://github.com/ecamo19/pysureau/blob/master/pysureau/conversions_utils.py#L666){target="_blank" style="float:right; font-size:smaller"}

### global_radiation_conversions_watts_ppfd

>      global_radiation_conversions_watts_ppfd (rg_ppfd:float=None,
>                                               rg_watts:float=None,
>                                               j_to_mol:float=4.6,
>                                               frac_par:float=0.5, selected_con
>                                               version:str='rg_watts_to_rg_ppfd
>                                               _umol')

*Convert Global Radiation (rg) in watts to Photosynthetic Photon Flux Density (ppfd) in umol and viceversa*

|    | **Type** | **Default** | **Details** |
| -- | -------- | ----------- | ----------- |
| rg_ppfd | float | None | Photosynthetic photon flux density (umol.m-2.s-1) |
| rg_watts | float | None | Global radiation (W/m2) |
| j_to_mol | float | 4.6 | Conversion factor |
| frac_par | float | 0.5 | Fraction of solar radiation that is photosynthetically active radiation (PAR) |
| selected_conversion | str | rg_watts_to_rg_ppfd_umol | String indicating to what units rg should be converted. Options 'rg_ppfd_umol_to_rg_watts' or 'rg_watts_to_rg_ppfd_umol' |
| **Returns** | **float** |  |  |


#### __Example: Calculate Global radiation in Watts and in PPFD__

::: {#cell-70 .cell}
``` {.python .cell-code}
global_radiation_conversions_watts_ppfd(
    rg_watts=7,
    j_to_mol=4.6,
    frac_par=0.5,
    selected_conversion='rg_watts_to_rg_ppfd_umol',
)
```

::: {.cell-output .cell-output-stdout}
```
Global radiation (rg) converted from watts to ppfd
```
:::

::: {.cell-output .cell-output-stderr}
```
/tmp/ipykernel_613/1345094339.py:41: UserWarning: Using j_to_mol default value of 4.6
  warnings.warn('Using j_to_mol default value of 4.6')
/tmp/ipykernel_613/1345094339.py:44: UserWarning: Using frac_par default value of 0.5
  warnings.warn('Using frac_par default value of 0.5')
```
:::

::: {.cell-output .cell-output-display}
```
16.099999999999998
```
:::
:::


::: {#cell-71 .cell}
``` {.python .cell-code}
global_radiation_conversions_watts_ppfd(
    rg_ppfd=9,
    j_to_mol=4.6,
    frac_par=0.5,
    selected_conversion='rg_ppfd_umol_to_rg_watts',
)
```

::: {.cell-output .cell-output-stdout}
```
Global radiation (rg) converted from ppfd to watts
```
:::

::: {.cell-output .cell-output-stderr}
```
/tmp/ipykernel_10557/2430486604.py:40: UserWarning: Using j_to_mol default value of 4.6
  warnings.warn('Using j_to_mol default value of 4.6')
/tmp/ipykernel_10557/2430486604.py:43: UserWarning: Using frac_par default value of 0.5
  warnings.warn('Using frac_par default value of 0.5')
```
:::

::: {.cell-output .cell-output-display}
```
3.91304347826087
```
:::
:::


::: {#cell-72 .cell}
``` {.python .cell-code}
global_radiation_conversions_watts_ppfd(
    rg_watts=5,
    j_to_mol=4.6,
    frac_par=0.5,
    selected_conversion='rg_watts_to_rg_ppfd_umol',
)
```

::: {.cell-output .cell-output-stdout}
```
Global radiation (rg) converted from watts to ppfd
```
:::

::: {.cell-output .cell-output-stderr}
```
/tmp/ipykernel_10557/2430486604.py:40: UserWarning: Using j_to_mol default value of 4.6
  warnings.warn('Using j_to_mol default value of 4.6')
/tmp/ipykernel_10557/2430486604.py:43: UserWarning: Using frac_par default value of 0.5
  warnings.warn('Using frac_par default value of 0.5')
```
:::

::: {.cell-output .cell-output-display}
```
11.5
```
:::
:::


---

[source](https://github.com/ecamo19/pysureau/blob/master/pysureau/conversions_utils.py#L721){target="_blank" style="float:right; font-size:smaller"}

### global_radiation_conversions_watts_mjules

>      global_radiation_conversions_watts_mjules (rg_watts:float=None,
>                                                 rg_mj:float=None,
>                                                 nhours:float=None, selected_co
>                                                 nversion:str='rg_watts_to_rg_m
>                                                 j')

*Convert instantaneous radiation in watts to daily cumulative radiation in MJ (MJ.day-1) and viceversa*

|    | **Type** | **Default** | **Details** |
| -- | -------- | ----------- | ----------- |
| rg_watts | float | None | Instantaneous radiation (watts) |
| rg_mj | float | None | Instantaneous radiation (in Mega Jules?) |
| nhours | float | None | Number of hours of sun in the day |
| selected_conversion | str | rg_watts_to_rg_mj | String indicating to what units rg should be converted. Options are 'rg_watts_to_rg_mj', 'rg_mj_to_rg_watts', 'rg_mj_to_rg_watts_hour', 'rg_watts_to_rg_mjday' or 'rg_mjday_to_rg_watts' |
| **Returns** | **float** |  |  |


#### __Example: Calculate Global radiation in Watts and in Mega Jules__

::: {#cell-75 .cell}
``` {.python .cell-code}
global_radiation_conversions_watts_mjules(
    rg_watts=300, selected_conversion='rg_watts_to_rg_mjday'
)
```

::: {.cell-output .cell-output-stdout}
```
Global radiation (rg) converted from watts to MegaJules per day
```
:::

::: {.cell-output .cell-output-display}
```
25.92
```
:::
:::


::: {#cell-76 .cell}
``` {.python .cell-code}
global_radiation_conversions_watts_mjules(
    rg_mj=25.92, selected_conversion='rg_mj_to_rg_watts'
)
```

::: {.cell-output .cell-output-stdout}
```
Global radiation (rg) converted from Mega Jules to Watts
```
:::

::: {.cell-output .cell-output-display}
```
300.0
```
:::
:::


::: {#cell-77 .cell}
``` {.python .cell-code}
global_radiation_conversions_watts_mjules(
    rg_mj=np.array([1, 2]),
    nhours=1,
    selected_conversion='rg_mj_to_rg_watts_hour',
)
```

::: {.cell-output .cell-output-stdout}
```
Global radiation (rg) converted from Mega Jules to Watts per hour
```
:::

::: {.cell-output .cell-output-display}
```
array([277.77777778, 555.55555556])
```
:::
:::


::: {#cell-78 .cell}
``` {.python .cell-code}
global_radiation_conversions_watts_mjules(
    rg_mj=10, nhours=10, selected_conversion='rg_mj_to_rg_watts_hour'
)
```

::: {.cell-output .cell-output-stdout}
```
Global radiation (rg) converted from Mega Jules to Watts per hour
```
:::

::: {.cell-output .cell-output-display}
```
277.77777777777777
```
:::
:::


---

[source](https://github.com/ecamo19/pysureau/blob/master/pysureau/conversions_utils.py#L814){target="_blank" style="float:right; font-size:smaller"}

### declination

>      declination (day_of_year:int, day_of_spring:int=80)

*Calculate declination of sun (radians ? ) for a given julian day (DOY)*

|    | **Type** | **Default** | **Details** |
| -- | -------- | ----------- | ----------- |
| day_of_year | int |  | julian day (day of the year) |
| day_of_spring | int | 80 | Julian day representing the first day of spring |
| **Returns** | **float** |  | **Earth declination at day_of_year** |


#### __Example: Calculate declination__

::: {#cell-81 .cell}
``` {.python .cell-code}
declination(day_of_year=90, day_of_spring=80)
```

::: {.cell-output .cell-output-stderr}
```
/tmp/ipykernel_613/1608233118.py:48: UserWarning: date of spring set to 80. This might change for Australia
  warnings.warn(
```
:::

::: {.cell-output .cell-output-display}
```
0.06835636102670284
```
:::
:::


::: {#cell-82 .cell}
``` {.python .cell-code}
declination(day_of_year=np.array([100, 200]), day_of_spring=80)
```

::: {.cell-output .cell-output-stderr}
```
/tmp/ipykernel_613/1608233118.py:48: UserWarning: date of spring set to 80. This might change for Australia
  warnings.warn(
```
:::

::: {.cell-output .cell-output-display}
```
array([0.1349969 , 0.35853539])
```
:::
:::


---

[source](https://github.com/ecamo19/pysureau/blob/master/pysureau/conversions_utils.py#L868){target="_blank" style="float:right; font-size:smaller"}

### potential_par

>      potential_par (time_of_day_in_hours:float, latitude:float,
>                     day_of_year:int)

*Determine potential for a given place and date /used to determine cloud cover return potential par in W.m2*

|    | **Type** | **Details** |
| -- | -------- | ----------- |
| time_of_day_in_hours | float | Array containing the time of the day (in hours) for which potential par should be calculated |
| latitude | float | Numeric value specifying the geographic latitude (in decimal degrees) of the location of interest |
| day_of_year | int | Julian day (day of the year) |
| **Returns** | **array** | **Potential Photosynthetic Active Radiation (PAR) for each time_of_day at given latitude and given day_of_year** |


#### __Example: Calculate the Potential PAR__

::: {#cell-85 .cell}
``` {.python .cell-code}
potential_par(time_of_day_in_hours=19, latitude=45.1, day_of_year=100)
```
:::


::: {#cell-86 .cell}
``` {.python .cell-code}
potential_par(
    time_of_day_in_hours=np.arange(0, 24), latitude=45.1, day_of_year=100
)
```
:::


