# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/pysureau',
                'doc_host': 'https://ecamo19.github.io',
                'git_url': 'https://github.com/ecamo19/pysureau',
                'lib_path': 'pysureau'},
  'syms': { 'pysureau.core': {'pysureau.core.foo': ('core.html#foo', 'pysureau/core.py')},
            'pysureau.pysureau_utils': { 'pysureau.pysureau_utils.pysureau_init': ( 'pysureau_utils.html#pysureau_init',
                                                                                    'pysureau/pysureau_utils.py')}}}
