# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/05_create_modeling_options.ipynb.

# %% auto 0
__all__ = ['create_empty_modeling_options_file']

# %% ../nbs/05_create_modeling_options.ipynb 3
import os
import random
import shutil
import datetime
import collections
import numpy as np
from typing import Dict
from pathlib import Path, PosixPath

# %% ../nbs/05_create_modeling_options.ipynb 5
def create_empty_modeling_options_file(
    path: Path,  # Path to the folder where the parameter files will be saved. If set to None then the files will be saved at the current working directory
) -> Dict:  # Return two dictionary file for user input
    "Function for creating the CSV templates necessary for the modeling options file"
    
    # Assert parameters ---------------------------------------------------------
    assert isinstance(path, str) | isinstance(path, PosixPath), (
        f'Input path must be a str, not a {type(path).__name__}'
    )
    
    # Convert string to Path if provided ----------------------------------------
    path = Path(path)
    
    # Main
    if os.path.exists(path):
        # Soil parameters for van Genuchten pedo transfer function
        modeling_options_params = {
            'comp_options_for_evapo' : 'normal',       
            'constant_climate' : False,
            'custom_small_time_step_in_sec' : 600,
            'defoliation' : False,
            'eord' : 1,
            'latitude' : 'NA',
            'lcav' : 1,
            'longitude': 'NA',
            'numerical_scheme': 'implicit',
            'output_overwrite': False,
            'output_path' : '/pysureau_project_EDITME/2_model_outputs',
            'output_type' : 'simple',
            'pet_formulation' : 'pt',
            'print_prog' : True,
            'resolution_output' : 'subdaily',
            'rn_formulation' : 'linacre',
            'scav': 1,
            'stomatal_reg_formulation':'sigmoid',
            'threshold_mortality': 90,
            'time_step_for_evapo': 1,
            'transpiration_granier_arg_a':-0.006,
            'transpiration_granier_arg_b':0.134,
            'transpiration_granier_arg_c':0,
            'transpiration_model':'jarvis',
            'year_end':'',
            'year_start':''            
        }

