# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/10_prepare_soil_parameters.ipynb.

# %% auto #0
__all__ = []

# %% ../nbs/10_prepare_soil_parameters.ipynb #d7f2acbe
import os
import warnings
import collections
import numpy as np
from pathlib import Path
from typing import Dict, List
from dataclasses import dataclass, field
from pysureau.soil_utils import (
    read_soil_file,
    compute_theta_at_given_p_soil,
    compute_theta_at_given_p_soil_camp,
)
from pysureau.conversions_utils import (
    convert_vwc_to_sws,
    convert_f_to_v
)
# from sureau_ecos_py.create_modeling_options import create_modeling_options
